### ISSUE TITLE
How to find if the Action generated by triggers happen successfully or not

### ISSUE THREAD

**Issue by IamSantosh** [zapier/visual-builder#133]
I'm working on an App on Zapier which helps in Sharing Post to Instagram Bussiness Account. My Issue is I've successfully created a trigger from my side which sends the Image URL & caption to Zapier. In trigger response, I received this.
{"id": "eeb23846-4a68-41d3-94ac-5a36fb3a9df7", "request_id": "5f6de14c-5bd5-4c98-8e58-309c5dc66da0", "attempt": "5f6de14c-5bd5-4c98-8e58-309c5dc66da0", "status": "success"}

But is there any way to find whether the Action is successfully triggered or not. For Action, we are using Instagram Bussiness App on Zapier.
Is there any callback or API using which we can find the response of Action.

**Comment by xavdid** [comment]
@IamSantosh Great question!

Since all actions in the Zapier backend happen asynchronously, **this isn't possible**. The `"status": "success"` message indicates that we've received your webhook and will process it "soon". Under normal operating conditions, this is basically instantly. If we're backed up or have slowed down task execution, we might not start the actions until later. Actions could also have multiple steps, some of which depend on each other. So while your specific case is pretty cut and dry, most aren't.

So all that is to say, currently that message is the only response we can give.
