### ISSUE TITLE
Request for a brief walk-through Zapier APIs

### ISSUE THREAD

**Issue by bpatel-sinch** [zapier/visual-builder#173]
Hello,

Is there any possibility to get brief 30 mins of your team's help so I can determine which specific Zapier APIs that my dev team may be able to leverage to pull together the integration as shown in the attached diagram. 

![image](https://user-images.githubusercontent.com/77173950/107595565-02950180-6be3-11eb-96c3-182d27c0304e.png)

Sinch is a market leader in CPaas (Communication Platform as a Service). Our clients -- based worldwide -- use Sinch cloud based CPaaS to engage with their users using mobile messaging technology such as SMS, MMS, RCS, WhatsApp, Viber, etc.

Sinch is OK to pull its own resource to create the app which will allow clients to use Zapier platform to send outbound messages using Sinch CPaaS. However, before we proceed on this activity, we just need brief help to see which specific APIs that Sinch Dev team can leverage to develop the integration as noted in the diag.

Please let us know when you may have few mins for the requested call. Thanks.

Bipin Patel
Email: bipin.patel@sinch.com

**Comment by xavdid** [comment]
@bpatel-sinch Hi there! As a rule, we don't do calls because our team is spread out and works better with asynchronous communication. 

In any case, the Zapier integration you're describing should encompass this:

![](https://cdn.zappy.app/dd219a7fbb0ea0184a0afe0fa0ab87cb.png)

I'm not sure what APIs your company maintains, but you would use the tools documented [here](https://platform.zapier.com/) to bridge the gap between Zapier and Sinch. For instance, you'd write integration code to call your "send facebook message API". Once that's ready, any user could authenticate with your service and use that integration to send FB messages from anywhere. 

Does that make sense?

**Comment by bpatel-sinch** [comment]
Hi David,

The link that you provided, it takes me to the following: https://platform.zapier.com/

So which Zapier APIs that we can leverage to send outbound mobile message (such as SMS, image, video) from Zapier to end-users using Sinch demo app and Sinch Rich Messaging server? Can you be specific of the exact APIs that we ought to be using for this use case? Thanks.

Bipin Patel

**Comment by xavdid** [comment]
Zapier doesn't expose APIs for this purpose directly. Instead, you'll be writing Node.js code (or using our Visual Builder). 

There's a quick start guide: https://platform.zapier.com/cli_docs/docs#quick-setup-guide

There's also example apps. It sounds like for your use case, you'll want to add "Create" steps. There's an example of that here: https://github.com/zapier/zapier-platform/tree/f7d5caf232b72989b12ed0a8063349931491ca36/example-apps/create.

I would run the following to get started:

First, install Node.js on a development machine if it's not available already. Then:

```sh
$ npm install -g zapier-platform-cli
$ zapier init sinch-app
$ cd sinch-app
$ npm install
$ zapier scaffold create send-message
```

That will give you an example app to work from. You'll then need to replace the urls in the `create-messag.js` file with Sinch's API urls.

Does that clear it up a bit?

**Comment by bpatel-sinch** [comment]
Hi David,

Once again, thank you for your below reply.  I was a software developer at one point in my life; however, over last 15+ years, I have been mostly focused on the product Management role. As such I had pulled in Thong (cc) in this conversation.

He is my developer assisting on this project. I need to make sure that Thong understands the process and steps fully.

Certainly I have an interest to know this fully as well; however, when it comes to the coding, I will hand over the task to Thong. 😊

Lastly can do REPLY ALL so Thong also see any new updates?


Hi Thong, Can I ask you to review / respond to David please?  Thanks.

Bipin Patel

**Comment by xavdid** [comment]
We can't reply-all because these are public comments on a github issue (https://github.com/zapier/visual-builder/issues/173). That said, I'll go ahead and close this issue out. You can write into partners@zapier.com if you want a more traditional email experience. That might be better for your use case.

If you (or Thong) are looking for a simpler development experience, https://developer.zapier.com/ is also a great option!
