### ISSUE TITLE
{{bundle.subscribeData}} is empty and impossible to diagnose

### ISSUE THREAD

**Issue by ansonkao** [zapier/visual-builder#42]
**Describe the bug**
I'm currently trying to configure a trigger, and can't figure out how to use `{{bundle.subscribeData}}` correctly. For auth, `{{bundle.auth.jwt}}` is working nicely for me, when I try to grab the resulting webhook id that was created in the subscribe portion, so that I can tell Zapier the correct URI to unsubscribe from, I can't figure out how to do it. The UI by default suggests using {{bundle.subscribeData.id}}, but when I test it, it does not populate the value and fires off the request as `https://domain.com/api/v1/feature/{{bundle.subscribeData.id}}` which is of course wrong. 

I tried doing `https://domain.com/api/v1/feature/{{bundle.targetUrl}}` which injects successfully. So injection is working, but `subscribeData.id` is either the wrong key or not being populated from the subscribe request.

![image](https://user-images.githubusercontent.com/300092/61160748-b77ab000-a4ce-11e9-80c0-60bc1dc35ac5.png)

**Expected behavior**

The UI should articulate all possible values that are valid for `{{bundle.validKey}}`, and warn the user if they are using an invalid key `{{bundle.invalidKey}}`. 

If my subscribe endpoint returns a response body that looks like this:
```
{
  "id": "ID_OF_THE_WEBHOOK",
  "someOtherKey": 12345678
}
```
There should be a box perhaps that displays a what is continued inside `{{bundle}}` so the developer knows where the ID is.

**Browser Info**

 - OS: macOS Mojave
 - Chrome
 - 74.0.3729.169 

**Additional context**

I'm running a trial to validate if integration is feasible.

**Comment by Risto995** [comment]
I ran into the same issue. The entire subscribe data object is empty and I don't know how to retrieve ID of the webhook in order to delete it on target API. Can anyone help?

**Comment by xavdid** [comment]
@ansonkao @Risto995 hey folks! sorry for the confusion here. 

The reason that your subscribe data is blank during the test is that there's not an actual zap running- it's just a stateless test request. Because of that, the unsubscribe doesn't know anything about your previous subscribe test.

We've got a help doc about this exact thing here: https://platform.zapier.com/docs/faq#how-do-i-define-rest-hooks-and-use-the-embedded-tester-with-them

You can follow the instructions in that doc, or set it up how you think it'll work and create a real zap. In either case, that should work as expected.

​Let me know if you've got any other questions!

**Comment by ejbeaty** [comment]
@xavdid it would be very helpful if this was made evident in the UI where you test subscribe/unsubscribe rest hooks. I too fell into the trap of expecting the {{bundle.subscribeData}} object to have a value because the UI insinuates it's using real account data by having you select a connection
![image](https://user-images.githubusercontent.com/1204924/86386724-6750ac80-bc4f-11ea-94bf-9d93d23611d0.png)

**Comment by roma2341** [comment]
Can i use {{bundle.targetUrl}} to unsubscribe ?
