### ISSUE TITLE
Triggers: Switching back and forth between REST hooks and Polling loses data

### ISSUE THREAD

**Issue by ansonkao** [zapier/visual-builder#43]
**Describe the bug**

I'm told to setup polling as a backup to rest hooks, but when I save a rest hook, and then I switch to polling to try to add polling, when I switch back to rest hooks all of my work is gone.

![image](https://user-images.githubusercontent.com/300092/61160807-f577d400-a4ce-11e9-94cc-2a7d0cd9d726.png)

----------------------------------

![image](https://user-images.githubusercontent.com/300092/61160858-37087f00-a4cf-11e9-8ef9-06c68dc05d22.png)

**Expected behavior**

It should maintain what's already saved in each of (a) REST hooks and (b) polling, regardless of which one is being edited at the moment.

**Browser Info**

 - OS: macOS Mojave
 - Chrome
 - 74.0.3729.169 

**Additional context**

I'm running a trial to validate if integration is feasible.

**Comment by matthewheath** [comment]
This is expected, if unintuitive, behaviour. The **Polling URL** mentioned here in the errors section is actually the **Perform List** endpoint URL shown when configuring the REST Hook on the API Configuration tab:

![](https://zappy.zapier.com/C3ED92CB-0A27-46B8-8706-2C18B2C66DFD.png)

I appreciate that's not made very clear - sorry about that.

At present, we don't save any configuration entered when switching between the two different setups. This is by design, but I'm going to raise this with our Developer Platform product team so they're aware of the level of interest in such a feature.

To get quicker support in the future, I recommend using the contact form at https://zapier.com/app/contact-us and selecting **Developing an app on the Zapier Platform** which will route the request to the relevant team.
