### ISSUE TITLE
No way to remove unused connections

### ISSUE THREAD

**Issue by ansonkao** [zapier/visual-builder#45]
**Describe the bug**

![image](https://user-images.githubusercontent.com/300092/61316307-b7c8c300-a7ce-11e9-89d9-e37075ba418b.png)

**To Reproduce**

`Test your API Request` > `Test Setup`

**Expected behavior**

Provide a delete button to remove old connections

**Comment by matthewheath** [comment]
You should be able to remove them from https://zapier.com/app/connections. I'll file a feature request to add a delete button to the tester as well.

If you need further help in the future, please use the contact form at https://zapier.com/app/contact-us and select the **Developing an app on the Zapier Platform** option in order to get faster support from us.
