### ISSUE TITLE
Incorrect variable name in GitHub's issue API endpoint

### ISSUE THREAD

**Issue by nthomas74** [zapier/visual-builder#98]
**Link to documentation with issue**

[Build Your Integration](https://platform.zapier.com/quickstart/build-trigger#3-configure-your-api)

**Describe the content issue**

This is part of the example integration with GitHub. The documentation provides you with GitHub's issue API endpoint for you to put into Trigger so that it will poll for new items. There are two variables within the endpoint. One for the GitHub username, the other for the repo name. The page reads as follows:

> Now, add the GitHub API call. Select the API Configuration tab in Zapier visual builder, choose the Polling option, then enter GitHub’s issue API endpoint in the field:
> 
> https://api.github.com/repos/{{bundle.inputData.username}}/{{bundle.inputData.repo}}/issues

At this point in the example integration, bundle.inputData.username does not exist. It should be bundle.authData.repo. The username was defined in the Authentication setup, whereas the repo was a form field we just created.

Thanks!

**Comment by matthewheath** [comment]
Hey there,

I think this is intentional - that Trigger should let you type the username and repo you want to monitor when setting up a Zap. Setting it as `{{bundle.authData.username}}` would mean that you'd only ever be scoped to the username of the GitHub account you connected to Zapier; it wouldn't let you monitor other public repos under different username namespaces.

The `bundle.inputData.username` variable will get set later on when you test that API endpoint and fill in the details. Hope that helps 🙂

**Comment by xavdid** [comment]
closing because Matthew says it's correct as is. Thanks for filing though @nthomas74!
